package com.androidlearning.databinding;

import android.os.Bundle;

import androidx.activity.EdgeToEdge;
import androidx.appcompat.app.AppCompatActivity;
import androidx.core.graphics.Insets;
import androidx.core.view.ViewCompat;
import androidx.core.view.WindowInsetsCompat;
import androidx.databinding.DataBindingUtil;

import com.androidlearning.R;

public class DataBindingActivity extends AppCompatActivity {

    //ActivityDataBindingBinding: name of binding class generated by the data binding library
    //derived from the name of XML file: Activity + {activity_name} + Binding(postfix)
    private ActivityDataBindingBinding dataBinding;
    private ClickHandler clickHandler;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        EdgeToEdge.enable(this);
        setContentView(R.layout.activity_data_binding);
        ViewCompat.setOnApplyWindowInsetsListener(findViewById(R.id.main), (v, insets) -> {
            Insets systemBars = insets.getInsets(WindowInsetsCompat.Type.systemBars());
            v.setPadding(systemBars.left, systemBars.top, systemBars.right, systemBars.bottom);
            return insets;
        });

        Person person = new Person("Jack", "jack@gmail.com");

        //set the content view to the specified layout resource
        //inflate the layout and generate the binding class that correspond to it
        dataBinding = DataBindingUtil.setContentView(this, R.layout.activity_data_binding);
        //passing person object(variable) to layout
        dataBinding.setPerson(person);

        //Binding the handler for click event
        clickHandler = new ClickHandler(this);
        //passing click handler(variable) to layout
        dataBinding.setClickHandler(clickHandler);

    }
}